### PR TITLE
Minor clean ups

### PR DESCRIPTION
**Pull request by megawac**
Just a couple minor things I noticed could be easily refactored doing a once over

Out of curiousity, why did you decide to implement many of the support functions over using `lodash` module implementations?

### CODE REVIEW

**Comment by jhusain** [comment]
@trxcllnt Do you mind giving these changes a quick look and confirming you approve?

**Comment by michaelbpaulson** [comment]
This is correct.  Ill re-kick travis as I think i have fixed the build issue.

**Comment by megawac** [comment]
I just did a `git commit --amend` and it seems travis is happy

**Comment by megawac** [comment]
> Out of curiousity, why did you decide to implement many of the support functions over using lodash/other existing implementations?

**Comment by trxcllnt** [comment]
> @megawac Out of curiousity, why did you decide to implement many of the support functions over using lodash/other existing implementations?

Mostly to ensure we can support our internal customers across a wide variety of JS environments. One of my goals is to slowly relax this standard going forward and factor as much of that stuff out as possible.

**Pull request merged**
