### PR TITLE
protect against model.invalidate(undefined) and model.invalidate([])

### PR DESCRIPTION
**Pull request by asyncanup**
from blowing away the entire cache

### CODE REVIEW

**Comment by benmj** [comment]
👏

**Comment by jhusain** [comment]
Worth discussion: Is TypeError the correct error to throw here? We'd like to move to nominal path types - ideally created via constructor - so that we don't have to keep running validation logic at every tier. We've always said that empty paths are invalid, because the root must be a Object. Under the circumstances should we consider an empty path a TypeError. Not sure if this is a misuse of TypeError. Certainly wouldn't be if we had a Path constructor so maybe we should wait until then to use TypeError?

**Comment by asyncanup** [comment]
@jhusain fine with making this a TypeError. Also cool with making this a `InvalidPathError` for that matter :)
Will let you make the final call.

**Comment by asyncanup** [comment]
@jhusain going to merge this, keeping existing `throw new Error` for now, instead of `TypeError` or `InvalidPathError`. Will make a new PR with your decision on that one once you're back

**Pull request merged**
