### PR TITLE
Remove webpack notice

### PR DESCRIPTION
**Pull request by adi-ads**
RxJS issue has been resolved and released, tested with falcor and works well.

### CODE REVIEW

**Comment by Dashed** [comment]
If it works, shouldn't this be removed then? https://github.com/Netflix/falcor/blob/master/webpack.config.js

**Comment by adi-ads** [comment]
Good point, deleted.

**Comment by sdesai** [comment]
Did you have a chance to test this off of npm?

When I looked at it last night, it was fixed on RxJS#master, and I tested it from there (https://github.com/Reactive-Extensions/RxJS/issues/832#issuecomment-132407081), but wanted to make sure it's working off of npm, out of the box, before removing the notice and config.

**Comment by sdesai** [comment]
It's also worth noting that this will bump up the RxJS dep from 2.x to 3.x, so that may need some validation, outside of the webpack issue [ unit tests, performance, regressions etc. ]

**Comment by adi-ads** [comment]
Only did it with local git clones, will try out with npm

**Comment by sdesai** [comment]
Cool. Thx. Although as mentioned above we may need to gate removing the webpack notice/config on determining whether or not we want to upgrade to RxJS 3.x in general, which is a broader decision, outside of the WebPack issue (for example https://github.com/Netflix/falcor/issues/464)

**Comment by dallonf** [comment]
This fix _is_ still needed for the version of RxJS listed in package.json, FYI, otherwise you'll run into bizarre issues where Observables don't have `reduce()` functions and the like.

I didn't RTFM. Don't be like me.

**Comment by sdesai** [comment]
I'm closing this out. We'll need the notice in place until we complete removal of RX as a core falcor dependency. See: https://github.com/Netflix/falcor/issues/465

**Pull request closed without merging**
